id: IA1BF771B
legacy_id: P000394
ocr_import_info:
  bdrc_scan_id: W1KG4225
  source: bdrc
  ocr_info:
    timestamp: '2020-03-17T18:44:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:25:37.214143+00:00'
last_modified: 2022-08-31 23:25:46.276368
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4225
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4225
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་ལྡན་མཁྱེན་བརྩེ་འོད་ཟེར་གྱི་རྣམ་ཐར་ཀུན་ཁྱབ་སྙན་པའི་བ་དན།
  author: བླ་མ་ཚེ་དབང་།
statistics:
  ocr_word_mean_confidence_index: 0.969669235585432
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1PD97416:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD97416
      total_pages: 186
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD97416.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.969669235585432
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
